apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: prod # Replace with your desired namespace
  labels:
    app: nginx
spec:
  replicas: 3 # Number of replicas for scaling
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: serv-docker.devops.tech.ec.europa.eu/modsps/nginx:v0.1.0 # Update this if necessary
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: my-registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: prod # Replace with your desired namespace
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 90        # Port that the service exposes
      targetPort: 80  # Port on the container
      nodePort: 30009 # Port on the node
